exp_name: 'inv_dd_gt_ema_mlp'
output_dir: './output/'

# dataset config
dataset:
  fn: './datasets/cifar10.py'
  name: 'CIFAR10'
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2470, 0.2435, 0.2616]
  num_classes: 10
  num_channel: 3

model:
  dim_m: 512
  dim_a: 4

train:
  adjust_iter_num: [40000]